### ISSUE TITLE
Can't build for some reason...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [russelarms/OffsetAnimator#4]
I get this:

Warning:One of the plugins you are using supports Java 8 language features. To try the support built into the Android plugin, remove the following from your build.gradle:
    apply plugin: 'me.tatarka.retrolambda'
To learn more, go to https://d.android.com/r/tools/java-8-support-message.html

Warning:One of the plugins you are using supports Java 8 language features. To try the support built into the Android plugin, remove the following from your build.gradle:
    apply plugin: 'me.tatarka.retrolambda'
To learn more, go to https://d.android.com/r/tools/java-8-support-message.html

Error:Execution failed for task ':app:transformClassesWithRetrolambdaForDebug'.
> Missing javaCompileTask for variant: debug/0 from output dir: D:\android\Android studio Projects\OffsetAnimator\app\build\intermediates\transforms\retrolambda\debug\0

![image](https://cloud.githubusercontent.com/assets/5357526/26765624/28298d34-4988-11e7-92b8-098f8517b1ea.png)

**Comment by russelarms** [comment]
Hello, can you show me your build.gradle files?

**Comment by AndroidDeveloperLB** [comment]
Sure, here:

![maxthonsnap20170605194155](https://cloud.githubusercontent.com/assets/5357526/26793552/0c8a227e-4a27-11e7-9465-4ac25a9aecb0.png)

I tried to update everything to the latest possible version, but it didn't help.

**Comment by russelarms** [comment]
Have you tried building project under stable Android Studio release (2.3.2) using `classpath com.android.tools.build:gradle:2.3.2` instead of  `com.android.tools.build:gradle:3.0.0-alpha3` ?

**Comment by AndroidDeveloperLB** [comment]
hmmm... I tried now on another PC, with 2.3.2 version of gradle, and it works fine...
Maybe you should report this issue to Google:
https://issuetracker.google.com/issues/new

**Comment by AndroidDeveloperLB** [comment]
Say, does the lines in the images appear on purpose?
I'm talking about this:

![device-2017-06-06-134554](https://cloud.githubusercontent.com/assets/5357526/26825647/89997606-4abe-11e7-8326-ea649f8596a4.png)

**Comment by russelarms** [comment]
This is an artifact of the image resource, we need to cut out the white edges.

**Comment by guanpj** [comment]
@AndroidDeveloperLB If want to use gradle 4.x version, you should remove the declare of retrorambda : apply plugin: 'me.tatarka.retrolambda'  in you build.gradle file. I have try it and it works.

**Comment by guanpj** [comment]
@AndroidDeveloperLB If want to use gradle 4.x version, you should remove the declare of retrorambda : apply plugin: 'me.tatarka.retrolambda' in your build.gradle file. I have try it and it works.

**Comment by guanpj** [comment]
@AndroidDeveloperLB If you want to use gradle 4.x version, you should remove the declare of retrorambda : apply plugin: 'me.tatarka.retrolambda' in your build.gradle file. I have try it and it works.

**Comment by man1088** [comment]
@guanpj Thank you so much, it worked.
